discord_bot_token:
discord_guild_name: Cultiststeve's playground

51_form_user:
51_form_pass:

ts_query_user:
ts_query_pass:

ts_url: localhost
ts_port: 10022

webdriver_host: http://localhost
webdriver_port: 4444

fuzzy_match_distance: 80