version: "3"



services:
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sausage
  ts3-server:
    image: teamspeak:3.13.6
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 10022:10022
      - 30033:30033
    environment:
      TS3SERVER_LICENSE: accept
      TS3SERVER_QUERY_PROTOCOLS: raw,ssh

